name: License Compliance Enforcement

on:
  push:
    branches: ["main", "master"]
  schedule:
    - cron: '0 1 * * 0' # weekly
  workflow_dispatch:

jobs:
  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests PyYAML

      - name: Check license compliance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/check_license_compliance.py

      - name: Upload compliance report
        uses: actions/upload-artifact@v4
        with:
          name: license-compliance-report
          path: license-compliance-report.md

  publish-report:
    runs-on: ubuntu-latest
    needs: license-compliance
    if: ${{ always() && needs.license-compliance.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download compliance report
        uses: actions/download-artifact@v4
        with:
          name: license-compliance-report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare site
        run: |
          mkdir -p _site
          cp license-compliance-report.md _site/index.md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 